services:
  maid:
    build: .
    image: maid-gpu-cu121:locked
    container_name: maid-container
    ports:
      - "8888:8888"
    volumes:
      - .:/workspace
      - ./hf_cache:/workspace/hf_cache   # HFキャッシュ永続化
    environment:
      - HF_TOKEN=${HF_TOKEN}
      - HF_HOME=/workspace/hf_cache
      - HF_HUB_ENABLE_HF_TRANSFER=1
      - VLLM_LOGGING_LEVEL=DEBUG
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 4
              capabilities: [gpu]
    stdin_open: true
    tty: true
    env_file:
      - .env
